version: 2

defaults: &defaults
  working_directory: ~/project/yarn
  docker:
    - image: yarnpkg/dev:latest

default_filters: &default_filters
  tags:
    only: '/^v[0-9]\+\.[0-9]\+\.[0-9]\+$/'

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - .cache/yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - yarn
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Tests
          command: |
            node -v
            if [ "$CIRCLE_BRANCH" == 'master' ]; then
              ./scripts/set-dev-version.js
            fi;
            yarn lint
            # Limit maxWorkers to 3 to avoid OOM on CircleCI
            yarn test-ci -- -- --maxWorkers 3
            yarn check-lockfile
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build distribution
          command: |
            node -v
            if [ "$CIRCLE_BRANCH" == 'master' ]; then
              ./scripts/set-dev-version.js
            fi;
            yarn build-dist
            ./scripts/build-deb.sh
      - store_artifacts:
          path: artifacts/
          destination: yarnpkg
      - persist_to_workspace:
          root: ~/project
          paths:
            - yarn
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy
          command: |
            echo 'deploy!'
            # Only NPM is handled here - All other release files are handled in a webhook.
            #if [ "${CIRCLE_PROJECT_USERNAME}" == "yarnpkg" ]; then
            #  if git describe --tags --abbrev=0 `git rev-parse HEAD` | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
            #    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            #    ./scripts/update-npm.sh
            #  fi
            #fi

notify:
  webhooks:
    # Handles uploading stable/RC releases to GitHub
    - url: https://nightly.yarnpkg.com/release_circleci
    # Handles archiving all builds onto the nightly build site
    - url: https://nightly.yarnpkg.com/archive_circleci

workflows:
  version: 2
  install-test-build-and-deploy:
    jobs:
      - install:
          filters: *default_filters
      - test:
          filters: *default_filters
          requires:
            - install
      - build:
          filters: *default_filters
          requires:
            - install
      - deploy:
          filters:
            <<: *default_filters
            branches:
              ignore: '/.*/'
          requires:
            - test
            - build
